title: Erkan Aksoy's Blog
description: Cybersecurity, Active Directory, Azure and Microsoft Entra ID
theme: minima
excerpt_separator: "<!--more-->"
show_excerpts: true

header_pages:
  - about.md
  - feed.xml          # or however RSS appears
  - photography.html

linkedin_url: https://www.linkedin.com/in/erkana/
